/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package raycasting;

import hsa2.GraphicsConsole;
import java.awt.Color;

public class App {
    GraphicsConsole gc = new GraphicsConsole(800, 600, "Raycasting Demo");

    Boundary wall;
    Ray ray;

    public static void main(String[] args) {
        new App();
    }

    App() {
        /* Set up GC */
        gc.setLocationRelativeTo(null);
        gc.setAntiAlias(true);
        gc.setBackgroundColor(Color.black);
        
        /* Create boundaries and rays */
        wall = new Boundary(gc, 300, 100, 300, 300);
        ray = new Ray(gc, 100, 200);

        /* Draw */

        while (true) {
            synchronized (gc) {
                gc.clear();

                wall.show();
                ray.show();
            }
            gc.sleep(2);
        }
    }
}
